ALTER TABLE Node ADD PRIMARY KEY (Id);
ALTER TABLE Way ADD PRIMARY KEY (Id);
ALTER TABLE Relation ADD PRIMARY KEY (Id);
CREATE INDEX ON Node USING HASH (Tags);
CREATE INDEX ON Way USING HASH (Tags);
CREATE INDEX ON Relation USING HASH (Tags);
CREATE INDEX ON Way USING HASH (Nodes);
CREATE INDEX ON Relation USING HASH (Members);
